// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package tool_test

import (
	"sync"
)

// converterMock is a mock implementation of tool.converter.
//
//	func TestSomethingThatUsesconverter(t *testing.T) {
//
//		// make and configure a mocked tool.converter
//		mockedconverter := &converterMock{
//			HTML2MDFunc: func(raw []byte) (string, error) {
//				panic("mock out the HTML2MD method")
//			},
//			PDF2MDFunc: func(raw []byte) (string, error) {
//				panic("mock out the PDF2MD method")
//			},
//		}
//
//		// use mockedconverter in code that requires tool.converter
//		// and then make assertions.
//
//	}
type converterMock struct {
	// HTML2MDFunc mocks the HTML2MD method.
	HTML2MDFunc func(raw []byte) (string, error)

	// PDF2MDFunc mocks the PDF2MD method.
	PDF2MDFunc func(raw []byte) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// HTML2MD holds details about calls to the HTML2MD method.
		HTML2MD []struct {
			// Raw is the raw argument value.
			Raw []byte
		}
		// PDF2MD holds details about calls to the PDF2MD method.
		PDF2MD []struct {
			// Raw is the raw argument value.
			Raw []byte
		}
	}
	lockHTML2MD sync.RWMutex
	lockPDF2MD  sync.RWMutex
}

// HTML2MD calls HTML2MDFunc.
func (mock *converterMock) HTML2MD(raw []byte) (string, error) {
	if mock.HTML2MDFunc == nil {
		panic("converterMock.HTML2MDFunc: method is nil but converter.HTML2MD was just called")
	}
	callInfo := struct {
		Raw []byte
	}{
		Raw: raw,
	}
	mock.lockHTML2MD.Lock()
	mock.calls.HTML2MD = append(mock.calls.HTML2MD, callInfo)
	mock.lockHTML2MD.Unlock()
	return mock.HTML2MDFunc(raw)
}

// HTML2MDCalls gets all the calls that were made to HTML2MD.
// Check the length with:
//
//	len(mockedconverter.HTML2MDCalls())
func (mock *converterMock) HTML2MDCalls() []struct {
	Raw []byte
} {
	var calls []struct {
		Raw []byte
	}
	mock.lockHTML2MD.RLock()
	calls = mock.calls.HTML2MD
	mock.lockHTML2MD.RUnlock()
	return calls
}

// PDF2MD calls PDF2MDFunc.
func (mock *converterMock) PDF2MD(raw []byte) (string, error) {
	if mock.PDF2MDFunc == nil {
		panic("converterMock.PDF2MDFunc: method is nil but converter.PDF2MD was just called")
	}
	callInfo := struct {
		Raw []byte
	}{
		Raw: raw,
	}
	mock.lockPDF2MD.Lock()
	mock.calls.PDF2MD = append(mock.calls.PDF2MD, callInfo)
	mock.lockPDF2MD.Unlock()
	return mock.PDF2MDFunc(raw)
}

// PDF2MDCalls gets all the calls that were made to PDF2MD.
// Check the length with:
//
//	len(mockedconverter.PDF2MDCalls())
func (mock *converterMock) PDF2MDCalls() []struct {
	Raw []byte
} {
	var calls []struct {
		Raw []byte
	}
	mock.lockPDF2MD.RLock()
	calls = mock.calls.PDF2MD
	mock.lockPDF2MD.RUnlock()
	return calls
}
